### PR TITLE
Added compatibility for Guardians of the Rift mini-game

### PR DESCRIPTION
**Pull request by jpeter17**
Updated runeLiteVersion ('1.6.35' -> '1.8.15.1')

Added Guardian Essence case to ItemID check

### CODE REVIEW

**Review by n-jones0 — APPROVED** [review]

**Comment by Pancake-Bun** [comment]
Any idea as to why my plugin would continue to not count Guardian Essence despite these changes? I'm not seeing much I can do on my end, so I was curious as to if it was user error or a bug. Thank you!

**Comment by jevonsp** [comment]
bumping this because i was pretty confused as to why it isnt working, still seems nonfunctional in gotr

**Comment by LameGames** [comment]
Why no merge

**Comment by JshGrn** [comment]
Is this not being merged?

**Comment by JshGrn** [comment]
@jpeter17 can you merge this in please?

**Comment by jjlabont** [comment]
@jpeter17 Can you merge this please?

**Comment by jpeter17** [comment]
I am not the owner of this project, @DavidVentura has to merge the PR

**Comment by itssapir** [comment]
@DavidVentura Can you please PR the plugin-hub git to update the plugin to include this latest commit?

**Comment by LameGames** [comment]
https://github.com/runelite/plugin-hub/blob/7002846b341a5331dd9e26762296a8f91069cd2e/plugins/rc-pouch-usage

Location for latest master commit hash to be updated I believe

**Comment by keoShine** [comment]
@DavidVentura Please PR this to the Plugin Hub.. Hella a pain not knowing when to expect my pouches to degrade mid-round since I don't have a Rune Pouch to carry NPC Contact runes that won't be deposited when dumping my crafted runes..

**Comment by JshGrn** [comment]
^ looks like the build failed as no 'author' set?

**Pull request merged**
